version: 2

machine:
  pre:
    - mkdir ~/.yarn-cache

dependencies:
  pre:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
  cache_directories:
    - ~/.yarn-cache
  override:
    - yarn install

jobs:
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

  release:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn make-npmrc
      - run: yarn lerna:publish

workflows:
  version: 2
  'continuously integrate':
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - build:
          requires:
            - test
      - release:
          filters:
            branches:
              only:
                - master
          requires:
            - build
