version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  release:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - release:
          requires:
            - test

deployment:
  production:
    branch: master
    commands:
      - git config --global user.email $GITHUB_EMAIL
      - git config --global user.name $GITHUB_USER
      - yarn lerna:publish
