version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

  release:
    docker:
      - image: circleci/node:10.13.0
    branches:
      only:
        - master
    steps:
      - checkout
      - yarn lerna:publish

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - build:
          requires:
            - test
      - release:
          requires:
            - build
