version: 2

machine:
  pre:
    - mkdir ~/.yarn-cache

dependencies:
  pre:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
  cache_directories:
    - ~/.yarn-cache
  override:
    - yarn install

jobs:
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn test --coverage
      - run: yarn coveralls

  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

  'build and release':
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: git config --global user.email "adam.raider@wework.com" && git config --global user.name "adamraider"
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: yarn lerna:publish

workflows:
  version: 2
  'continuously integrate':
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              ignore:
                - master
      - 'build and release':
          requires:
            - test
          filters:
            branches:
              only:
                - master
